steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    id: build-app-image
    timeout: 300s
    args:
      - --dockerfile=$_DOCKERFILE_PATH_APP
      - --destination=$_DOCKER_IMAGE_FULLNAME_APP
      - --cache=true
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest"
      - "--region"
      - "$_DEPLOY_REGION"
      - "--allow-unauthenticated"
      - --service-account
      - "$_SERVICE_ACCOUNT"
      - "--memory"
      - 256Mi
      - "--platform"
      - "managed"
      - "--timeout"
      - "600"
    timeout: "3600s"
options:
  dynamic_substitutions: true
substitutions:
  _VERSION: "1.4.0.2"
  _APP_NAME: rowy-hooks
  _ARCHITECTURE: backend
  _DEPLOY_REGION: europe-central2
  _SERVICE_NAME: ${_APP_NAME}-${BRANCH_NAME}
  _SERVICE_ACCOUNT: "rowy-hooks@${PROJECT_ID}.iam.gserviceaccount.com"

  _ARTIFACT_REGISTRY_HOSTNAME: europe-docker.pkg.dev
  _ARTIFACT_REGISTRY_REPOSITORY_NAME: ${_APP_NAME}
  _ARTIFACT_REGISTRY_REPOSITORY_PATH: ${_ARTIFACT_REGISTRY_HOSTNAME}/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY_NAME}

  _DOCKERFILE_PATH_APP: "./Dockerfile"
  _DOCKER_IMAGE_TAG_APP: ${_VERSION}
  _DOCKER_IMAGE_NAME_APP: ${_SERVICE_NAME}
  _DOCKER_IMAGE_FULLNAME_APP: ${_ARTIFACT_REGISTRY_REPOSITORY_PATH}/${_DOCKER_IMAGE_NAME_APP}:${_DOCKER_IMAGE_TAG_APP}
tags:
  - "${_SERVICE_NAME}"
  - "$BRANCH_NAME"
  - "${_ARCHITECTURE}"
